export const SERVER_URL = 'https://habs.sdf.org:8080/match';
export const GRAPHQL_ENDPOINT = 'https://cmqivfcisjb3viqolzsggmd3ea.appsync-api.eu-west-1.amazonaws.com/graphql';
export const headers = {
  'content-type': 'application/json',
  'x-api-key': 'da2-yhjrcquonnb3bncekqi5j2pggy',
};
export const SearchCompetitors = `query SearchCompetitors($query: String, $gender: GenderType, $disciplineCode: String, $environment: String, $countryCode: String) {
  searchCompetitors(query: $query, gender: $gender, disciplineCode: $disciplineCode, environment: $environment, countryCode: $countryCode) {
    aaAthleteId
    familyName
    givenName
    birthDate
    disciplines
    iaafId
    gender
    country
    urlSlug
    __typename
  }
}`;
export const GetCompetitorBasicInfo = `
query GetCompetitorBasicInfo($id: Int, $urlSlug: String) {
  competitor: getSingleCompetitor(id: $id, urlSlug: $urlSlug) {
    resultsByYear {
      activeYears
    }
  }
}`;
export const disciplines = [
  '50 Metres',
  '55 Metres',
  '60 Metres',
  '100 Metres',
  '100 Yards',
  '150 Metres',
  '200 Metres',
  '300 Metres',
  '400 Metres',
  '500 Metres',
  '600 Metres',
  '800 Metres',
  '1000 Metres',
  '1500 Metres',
  'One Mile',
  '2000 Metres',
  '3000 Metres',
  'Two Miles',
  '5000 Metres',
  '5 Kilometres',
  '8 Kilometres',
  '5 Miles Road',
  '10,000 Metres',
  '10 Kilometres',
  '12 Kilometres',
  '15,000 Metres',
  '15 Kilometres',
  'One Mile Road',
  '10 Miles Road',
  '20,000 Metres',
  '20 Kilometres',
  'One Hour',
  'Half Marathon',
  '25,000 Metres',
  '25 Kilometres',
  '30,000 Metres',
  '30 Kilometres',
  'Marathon',
  '50 Kilometres',
  '100 Kilometres',
  '24 Hours',
  '2000 Metres Steeplechase',
  '2000 Metres Steeplechase (84)',
  '3000 Metres Steeplechase',
  '50 Metres Hurdles',
  '55 Metres Hurdles',
  '60 Metres Hurdles',
  '60m Hurdles (91.4cm)',
  '60m Hurdles (99.0cm)',
  '60m Hurdles (76.2cm)',
  '80 Metres Hurdles',
  '100 Metres Hurdles',
  '110m Hurdles (99.0cm)',
  '100m Hurdles (76.2cm)',
  '110 Metres Hurdles',
  '110m Hurdles (91.4cm)',
  '200 Metres Hurdles',
  '300m Hurdles (84.0cm)',
  '300 Metres Hurdles',
  '400m hurdles (84.0cm)',
  '400 Metres Hurdles',
  'High Jump',
  'Pole Vault',
  'Long Jump',
  'Triple Jump',
  'Shot Put',
  'Shot Put (6kg)',
  'Shot Put (5kg)',
  'Shot Put (3kg)',
  'Shot Put (4kg)',
  'Discus Throw',
  'Discus Throw (1.750kg)',
  'Discus Throw (1.500kg)',
  'Hammer Throw',
  'Hammer Throw (6kg)',
  'Hammer Throw (5kg)',
  'Hammer Throw (3kg)',
  'Javelin Throw',
  'Javelin Throw (old)',
  'Javelin Throw (700g)',
  'Javelin Throw (500g)',
  'Pentathlon',
  'Pentathlon Girls',
  'Heptathlon',
  'Heptathlon U20',
  'Heptathlon-100mH 76.2cm',
  'Heptathlon Girls',
  'Heptathlon Boys',
  'Octathlon Boys',
  'Decathlon',
  'Decathlon (62-84)',
  'Decathlon U20',
  'Decathlon Boys',
  'One Mile Race Walk',
  '3000 Metres Race Walk',
  '5000 Metres Race Walk',
  '5 Kilometres Race Walk',
  '10,000 Metres Race Walk',
  '10 Kilometres Race Walk',
  '15 Kilometers Race Walk',
  '20,000 Metres Race Walk',
  '20 Kilometres Race Walk',
  '2 Hours Race Walk',
  '30,000 Metres Race Walk',
  '30 Kilometres Race Walk',
  '35 Kilometres Race Walk',
  '50,000 Metres Race Walk',
  '35,000 Metres Race Walk',
  '50 Kilometres Race Walk',
  '4x100 Metres Relay',
  '4x200 Metres Relay',
  '4x400 Metres Relay',
  '4x400 Metres Relay Mixed',
  'Mixed 2x2x400m Relay',
  'Shuttle Hurdles Relay',
  '4x800 Metres Relay',
  '4x1500 Metres Relay',
  'Medley Relay',
  '8x100 Metres Relay',
  'Road Relay',
  'Distance Medley Relay',
  'Mixed Relay',
  'One Hour Walk',
  'Senior Race',
  'Cross Country',
  'U20 Race',
  'U23 Race',
  'Short Race',
  'Long Race',
  '20libs Weight',
  '35libs Weight',
  'Cross Country 4000m',
  '100m Blind',
  '200m Blind',
  '400m Blind',
  '100m Wheelchair',
  '200m Wheelchair',
  '1500m Wheelchair',
  '800m Wheelchair',
  'Javelin Throw Wheelchair',
  '200m Amputee',
  '100m Amputee',
  '400m Cereb. Palsy',
  '200m Visually Impaired',
  '400 Metres T53',
  '800 Metres T54',
  '400m Masters',
  '800m Masters',
] as const;
export const commonDisciplines: (typeof disciplines)[number][] = [
  // '50 Metres',
  // '55 Metres',
  '60 Metres',
  '100 Metres',
  // '100 Yards',
  // '150 Metres',
  '200 Metres',
  // '300 Metres',
  '400 Metres',
  // '500 Metres',
  '600 Metres',
  '800 Metres',
  // '1000 Metres',
  '1500 Metres',
  'One Mile',
  // '2000 Metres',
  '3000 Metres',
  'Two Miles',
  '5000 Metres',
  // '5 Kilometres',
  // '8 Kilometres',
  // '5 Miles Road',
  '10,000 Metres',
  // '10 Kilometres',
  // '12 Kilometres',
  // '15,000 Metres',
  // '15 Kilometres',
  // 'One Mile Road',
  // '10 Miles Road',
  // '20,000 Metres',
  // '20 Kilometres',
  // 'One Hour',
  'Half Marathon',
  // '25,000 Metres',
  // '25 Kilometres',
  // '30,000 Metres',
  // '30 Kilometres',
  'Marathon',
  // '50 Kilometres',
  // '100 Kilometres',
  // '24 Hours',
  // '2000 Metres Steeplechase',
  // '2000 Metres Steeplechase (84)',
  '3000 Metres Steeplechase',
  // '50 Metres Hurdles',
  // '55 Metres Hurdles',
  '60 Metres Hurdles',
  // '60m Hurdles (91.4cm)',
  // '60m Hurdles (99.0cm)',
  // '60m Hurdles (76.2cm)',
  // '80 Metres Hurdles',
  '100 Metres Hurdles',
  // '110m Hurdles (99.0cm)',
  // '100m Hurdles (76.2cm)',
  '110 Metres Hurdles',
  // '110m Hurdles (91.4cm)',
  // '200 Metres Hurdles',
  // '300m Hurdles (84.0cm)',
  // '300 Metres Hurdles',
  // '400m hurdles (84.0cm)',
  '400 Metres Hurdles',
  '20 Kilometres Race Walk',
  '35 Kilometres Race Walk',
  'High Jump',
  'Pole Vault',
  'Long Jump',
  'Triple Jump',
  'Shot Put',
  // 'Shot Put (6kg)',
  // 'Shot Put (5kg)',
  // 'Shot Put (3kg)',
  // 'Shot Put (4kg)',
  'Discus Throw',
  // 'Discus Throw (1.750kg)',
  // 'Discus Throw (1.500kg)',
  'Hammer Throw',
  // 'Hammer Throw (6kg)',
  // 'Hammer Throw (5kg)',
  // 'Hammer Throw (3kg)',
  'Javelin Throw',
  // 'Javelin Throw (old)',
  // 'Javelin Throw (700g)',
  // 'Javelin Throw (500g)',
  // 'Pentathlon',
  // 'Pentathlon Girls',
  'Heptathlon',
  // 'Heptathlon U20',
  // 'Heptathlon-100mH 76.2cm',
  // 'Heptathlon Girls',
  // 'Heptathlon Boys',
  // 'Octathlon Boys',
  'Decathlon',
];
export const MAX_ATHLETES = 12;
